export const RECIVE_LIMITSHOP = 'recive_limitShop'
export const RECIVE_POLICY = 'recive_policy'
export const RECIVE_NEWPRODUCTS = 'recive_newProducts'
export const RECIVE_CATEGORYS = 'recive_categorys'
export const RECIVE_SHOP_GUIDE = 'recive_shop_guide'
export const RECIVE_PERSONAL_SHOP = 'recive_personal_shop'